import { useQuery } from '@tanstack/react-query'
import { localStore } from './localStore'

/*
 * 13-line IndoPak (Taj Company) Mushaf, generated by scripts/build-quran.py from the
 * Quranic Universal Library. Served as a static file and precached by the service worker,
 * so it works fully offline.
 */

/** ["s", surah] surah header | ["b"] bismillah | ["a", centered, words] ayah line */
export type MushafLine = ['s', number] | ['b'] | ['a', 0 | 1, string[]]

export type MushafPage = { juz: number; surah: number | null; lines: MushafLine[] }

export type Mushaf = {
  v: number
  bismillah: string
  surahs: { n: number; ar: string; en: string; ayahs: number; page: number }[]
  juz: { n: number; page: number }[]
  pages: MushafPage[]
}

export const LINES_PER_PAGE = 13

/** The printed Taj Company Mushaf has a title page first, so printed number = layout page + 1 */
export const PRINTED_PAGE_OFFSET = 1
export const printedPage = (layoutPage: number) => layoutPage + PRINTED_PAGE_OFFSET

export function useMushaf() {
  return useQuery({
    queryKey: ['mushaf', 'indopak-13'],
    queryFn: async () => {
      const res = await fetch('/mushaf/indopak-13.json')
      if (!res.ok) throw new Error(`Couldn't load the Quran (${res.status})`)
      return (await res.json()) as Mushaf
    },
    staleTime: Infinity,
    // Already cached by the service worker; keep it out of the IndexedDB query cache
    meta: { persist: false },
  })
}

/* Last page read, remembered on this device */
const LAST_PAGE_KEY = 'aamaal.quran.page'

export function getLastPage(): number {
  try {
    const n = Number(localStorage.getItem(LAST_PAGE_KEY))
    return Number.isInteger(n) && n >= 1 ? n : 1
  } catch {
    return 1
  }
}

export function saveLastPage(page: number) {
  try {
    localStorage.setItem(LAST_PAGE_KEY, String(page))
  } catch {
    /* storage unavailable */
  }
}

/* ------------------------------------------------------------------ */
/* One search across paras, surahs and pages                           */
/* ------------------------------------------------------------------ */

export type GotoResult = { key: string; kind: 'Para' | 'Surah' | 'Page'; title: string; ar?: string; page: number }

/** Lowercase, drop accents/punctuation/spaces: "Al-Fātiĥah" → "alfatihah" */
const normalize = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\u0600-\u06ff]/g, '')

/** Consonant skeleton of a normalized Latin name: "yaseen" → "ysn" */
const skeleton = (s: string) => normalize(s).replace(/[aeiou]/g, '')

export function searchMushaf(mushaf: Mushaf, raw: string): GotoResult[] {
  const q = raw.trim()
  if (!q) return []
  const results: GotoResult[] = []
  const num = Number(q.match(/\d+/)?.[0])
  const wants = (kind: string) => !/[a-z]/i.test(q.replace(/\d+/g, '')) || new RegExp(kind, 'i').test(q)

  // Numbers: "3", "para 3", "juz 3", "surah 36", "page 57"
  if (num) {
    const juz = mushaf.juz[num - 1]
    if (juz && (wants('para') || wants('juz')))
      results.push({ key: `p${num}`, kind: 'Para', title: `Para ${num}`, page: juz.page })
    const surah = mushaf.surahs[num - 1]
    if (surah && wants('sur'))
      results.push({ key: `s${num}`, kind: 'Surah', title: `${surah.n}. ${surah.en}`, ar: surah.ar, page: surah.page })
    const layoutPage = num - PRINTED_PAGE_OFFSET
    if (layoutPage >= 1 && layoutPage <= mushaf.pages.length && wants('page'))
      results.push({ key: `g${num}`, kind: 'Page', title: `Page ${num}`, page: layoutPage })
  }

  // Surah names (English or Arabic)
  const nq = normalize(q.replace(/\b(surah|sura|surat)\b/gi, ''))
  // Vowel-free form so common spellings match: "yaseen" ≈ "Ya-Sin", "baqra" ≈ "Al-Baqarah"
  const nqSkel = skeleton(nq)
  if (nq && !/^\d+$/.test(nq)) {
    for (const s of mushaf.surahs) {
      if (
        normalize(s.en).includes(nq) ||
        normalize(s.ar).includes(nq) ||
        (nqSkel.length >= 2 && skeleton(s.en).includes(nqSkel))
      )
        results.push({ key: `s${s.n}`, kind: 'Surah', title: `${s.n}. ${s.en}`, ar: s.ar, page: s.page })
    }
  }

  // De-duplicate (a number can also match a surah name)
  return results.filter((r, i) => results.findIndex((x) => x.key === r.key) === i)
}

/* ------------------------------------------------------------------ */
/* Per-device reading state (localStorage), reactive across components */
/* ------------------------------------------------------------------ */

/** "Stopped here" mark: layout page + line index on that page */
export type ReadingMark = { page: number; line: number }
export const readingMark = localStore<ReadingMark | null>('aamaal.quran.mark', null)

/** Surahs people read often, for one-tap access (editable with the ☆ in the surah list) */
export const DEFAULT_FAVOURITE_SURAHS = [36, 56, 67, 18, 55, 32]
export const favouriteSurahs = localStore<number[]>('aamaal.quran.favs', DEFAULT_FAVOURITE_SURAHS)

export function toggleFavouriteSurah(n: number) {
  const cur = favouriteSurahs.read()
  favouriteSurahs.write(cur.includes(n) ? cur.filter((x) => x !== n) : [...cur, n])
}
